package com.jks.entity;

public class AuditSchool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditschool.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditschool.Admcode
     *
     * @mbg.generated
     */
    private String admcode;

    
    private String auditcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditschool.SchoolName
     *
     * @mbg.generated
     */
    private String schoolname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditschool.ID
     *
     * @return the value of auditschool.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditschool.ID
     *
     * @param id the value for auditschool.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditschool.Admcode
     *
     * @return the value of auditschool.Admcode
     *
     * @mbg.generated
     */
    public String getAdmcode() {
        return admcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditschool.Admcode
     *
     * @param admcode the value for auditschool.Admcode
     *
     * @mbg.generated
     */
    public void setAdmcode(String admcode) {
        this.admcode = admcode == null ? null : admcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditschool.Auditcode
     *
     * @return the value of auditschool.Auditcode
     *
     * @mbg.generated
     */
    public String getAuditcode() {
        return auditcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditschool.Auditcode
     *
     * @param auditcode the value for auditschool.Auditcode
     *
     * @mbg.generated
     */
    public void setAuditcode(String auditcode) {
        this.auditcode = auditcode == null ? null : auditcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditschool.SchoolName
     *
     * @return the value of auditschool.SchoolName
     *
     * @mbg.generated
     */
    public String getSchoolname() {
        return schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditschool.SchoolName
     *
     * @param schoolname the value for auditschool.SchoolName
     *
     * @mbg.generated
     */
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname == null ? null : schoolname.trim();
    }
}