package com.jks.entity;

public class SchoolInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolinfo.Admcode
     *
     * @mbg.generated
     */
    private String admcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolinfo.Area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolinfo.SchoolName
     *
     * @mbg.generated
     */
    private String schoolname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolinfo.SchoolAddr
     *
     * @mbg.generated
     */
    private String schooladdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolinfo.TeleNumber
     *
     * @mbg.generated
     */
    private String telenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolinfo.RunCode
     *
     * @mbg.generated
     */
    private String runcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolinfo.Admcode
     *
     * @return the value of schoolinfo.Admcode
     *
     * @mbg.generated
     */
    public String getAdmcode() {
        return admcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolinfo.Admcode
     *
     * @param admcode the value for schoolinfo.Admcode
     *
     * @mbg.generated
     */
    public void setAdmcode(String admcode) {
        this.admcode = admcode == null ? null : admcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolinfo.Area
     *
     * @return the value of schoolinfo.Area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolinfo.Area
     *
     * @param area the value for schoolinfo.Area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolinfo.SchoolName
     *
     * @return the value of schoolinfo.SchoolName
     *
     * @mbg.generated
     */
    public String getSchoolname() {
        return schoolname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolinfo.SchoolName
     *
     * @param schoolname the value for schoolinfo.SchoolName
     *
     * @mbg.generated
     */
    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname == null ? null : schoolname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolinfo.SchoolAddr
     *
     * @return the value of schoolinfo.SchoolAddr
     *
     * @mbg.generated
     */
    public String getSchooladdr() {
        return schooladdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolinfo.SchoolAddr
     *
     * @param schooladdr the value for schoolinfo.SchoolAddr
     *
     * @mbg.generated
     */
    public void setSchooladdr(String schooladdr) {
        this.schooladdr = schooladdr == null ? null : schooladdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolinfo.TeleNumber
     *
     * @return the value of schoolinfo.TeleNumber
     *
     * @mbg.generated
     */
    public String getTelenumber() {
        return telenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolinfo.TeleNumber
     *
     * @param telenumber the value for schoolinfo.TeleNumber
     *
     * @mbg.generated
     */
    public void setTelenumber(String telenumber) {
        this.telenumber = telenumber == null ? null : telenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolinfo.RunCode
     *
     * @return the value of schoolinfo.RunCode
     *
     * @mbg.generated
     */
    public String getRuncode() {
        return runcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolinfo.RunCode
     *
     * @param runcode the value for schoolinfo.RunCode
     *
     * @mbg.generated
     */
    public void setRuncode(String runcode) {
        this.runcode = runcode == null ? null : runcode.trim();
    }

	@Override
	public String toString() {
		return "SchoolInfo [admcode=" + admcode + ", area=" + area
				+ ", schoolname=" + schoolname + ", schooladdr=" + schooladdr
				+ ", telenumber=" + telenumber + ", runcode=" + runcode + "]";
	}
    
}