package com.jks.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jks.entity.Partybulid;

public interface PartybulidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partybulid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partybulid
     *
     * @mbg.generated
     */
    int insert(Partybulid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partybulid
     *
     * @mbg.generated
     */
    int insertSelective(Partybulid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partybulid
     *
     * @mbg.generated
     */
    Partybulid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partybulid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Partybulid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partybulid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Partybulid record);

	List<Partybulid> getPartyBulidList(@Param("admcode")String admcode,@Param("year")String year);
	
	void savePartyBulid(Partybulid partybulid);

	boolean deletePartyBulid(int id);

	Partybulid findById(int id);

	boolean updatePartyBulid(Partybulid partybulid);

	boolean updateAudit(int id);

	List<Partybulid> findByCity(@Param("city")String city,@Param("year")String year);

	List<Partybulid> getPartyBulidListByAdmin(@Param("admcode")String admcode,@Param("year")String year);

	List<Partybulid> adminFindByCity(@Param("city")String city,@Param("year")String year);

	Integer checkYear(Partybulid partybulid);


}